name: Test and Lint

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Lint
        run: deno lint
      - name: Test
        run: deno test --allow-all --coverage=cov/
      - name: Generate coverage
        run: deno coverage --lcov cov/ > cov.lcov
